### PR TITLE
graphPaper Fix

### PR DESCRIPTION
**Pull request by jandricd**
Fixed crashing when size of 0 is used for graphPaper.

### CODE REVIEW

**Comment by GordonBGood** [comment]
What about `graphPaperCustom`, which has the same problem?

For `graphPaperCustom`, you might want to check that the line thickness doesn't exceed the line spacing, else we'll get a solid graph paper.

**Comment by jandricd** [comment]
Great idea, implemented!

**Comment by GordonBGood** [comment]
You fixed the line thickness, but what about not accepting spacing `s` < 2 so it works like the non-Custom function?

Also, remember that both `s` and `th` are `Float`s, so there is still no reason that `s` couldn't be 1.0 and `th` 1.00001 so as still to get a solid graph paper for all practical purposes.

**Comment by CSchank** [comment]
I think we won't bother with the second fix. They should understand that doing so would lead to weird results, having it fail silently like that is kind of confusing I think. Also, instead of fixing `graphPaper`, I'll just fix `graphPaperCustom`. I'll merge it and then make changes. Thanks to both of you!

**Pull request merged**
